### ISSUE TITLE
Texture Issue with Long Skirt in Inference Results

### ISSUE THREAD

**Issue by LeslieZhoa** [Dolorousrtur/ContourCraft#2]
Thank you for the outstanding work you've done! I encountered some issues regarding the visual output during the inference process. Following the instructions in Inference.ipynb, I set the garments to longskirt and the pose to CMU/01/01_01_poses.npz.

I only exported the visualization for the first frame
```py
objects = []
objects += add_seq(sequence_path, cloth_color=cmap(0.))
import trimesh 
mm = trimesh.Trimesh(objects[0].vertices[0],objects[0].faces)
mm.export('clt3.obj')
mm = trimesh.Trimesh(objects[1].vertices[0],objects[1].faces)
mm.export('body3.obj')
```
 and here is the result:
![image](https://github.com/user-attachments/assets/ced1a69f-e8d4-447f-af68-1a017c5d66cd)

However, I noticed some issues with the texture of the skirt. Could you please let me know if I made any mistakes during the inference process? I look forward to your response. Thank you!

**Comment by Dolorousrtur** [comment]
This is normal. This is just an initial geometry generated by linear blend skinning and not the result of actual simulation. It is used to start the simulation from. So if you look into the geometries in any subsequent frame they will not have such artifacts

**Comment by LeslieZhoa** [comment]
Thanks! It goes well!
